use crate::Word;

pub const INPUT_SERVICE_REQUEST_SUBSCRIBE: Word = 0x6101;
pub const INPUT_SERVICE_REQUEST_READ_EVENT: Word = 0x6102;
pub const INPUT_SERVICE_REQUEST_ATTACH_DRIVER: Word = 0x6103;
pub const INPUT_SERVICE_REQUEST_SUBSCRIBE_SHARED: Word = 0x6104;
pub const INPUT_SERVICE_REQUEST_ATTACH_DRIVER_SHARED: Word = 0x6105;
pub const INPUT_SERVICE_REQUEST_PUBLISH_EVENT: Word = 0x61f0;

pub const INPUT_SUBSCRIBE_KEYBOARD: Word = 1 << 0;
pub const INPUT_SUBSCRIBE_MOUSE: Word = 1 << 1;
pub const INPUT_SUBSCRIBE_ALL: Word = INPUT_SUBSCRIBE_KEYBOARD | INPUT_SUBSCRIBE_MOUSE;
pub const INPUT_NOTIFICATION_IDENTIFIER: Word = 1 << 49;
pub const INPUT_DRIVER_NOTIFICATION_IDENTIFIER: Word = 1 << 50;

pub const INPUT_DRIVER_KEYBOARD: Word = 1;
pub const INPUT_DRIVER_MOUSE: Word = 2;

pub const INPUT_EVENT_KIND_KEY: Word = 1;
pub const INPUT_EVENT_KIND_MOUSE_BUTTON: Word = 2;
pub const INPUT_EVENT_KIND_MOUSE_MOVE: Word = 3;
pub const INPUT_EVENT_KIND_MOUSE_WHEEL: Word = 4;

pub const INPUT_EVENT_QUEUE_MAGIC: Word = 0x494e_5055_5451_3031;
pub const INPUT_EVENT_QUEUE_HEADER_WORDS: usize = 5;
pub const INPUT_EVENT_QUEUE_CAPACITY: usize = 1024;
pub const INPUT_EVENT_QUEUE_BYTES: Word = 0x4000;
