use crate::Word;

pub const NET_DEVICE_REQUEST_SEND: Word = 0x2001;
pub const NET_DEVICE_REQUEST_RECV: Word = 0x2002;
pub const NET_DEVICE_REQUEST_CONTROL: Word = 0x2003;

pub const NET_DEVICE_CONTROL_LINK_UP: Word = 1;
pub const NET_DEVICE_CONTROL_LINK_DOWN: Word = 2;
pub const NET_DEVICE_CONTROL_ATTACH_SHARED_MEMORY: Word = 16;
pub const NET_DEVICE_CONTROL_GET_MAC: Word = 17;

pub const NET_SERVICE_REQUEST_SEND: Word = 0x3001;
pub const NET_SERVICE_REQUEST_RECV: Word = 0x3002;
pub const NET_SERVICE_REQUEST_CONTROL: Word = 0x3003;
pub const NET_SERVICE_REQUEST_STATS: Word = 0x3004;
pub const NET_SERVICE_REQUEST_UDP_SEND: Word = 0x3010;
pub const NET_SERVICE_REQUEST_UDP_RECV: Word = 0x3011;
pub const NET_SERVICE_REQUEST_TCP_SEND: Word = 0x3020;
pub const NET_SERVICE_REQUEST_TCP_RECV: Word = 0x3021;
pub const NET_SERVICE_REQUEST_DNS_QUERY: Word = 0x3030;

pub const NET_SERVICE_CONTROL_LINK_UP: Word = 1;
pub const NET_SERVICE_CONTROL_LINK_DOWN: Word = 2;
pub const NET_SERVICE_CONTROL_POLL: Word = 3;
pub const NET_SERVICE_CONTROL_ATTACH_SHARED_MEMORY: Word = 16;
pub const NET_SERVICE_CONTROL_GET_IPV4_CONFIG: Word = 17;
pub const NET_SERVICE_CONTROL_GET_MAC: Word = 18;
pub const NET_SERVICE_CONTROL_UDP_BIND: Word = 32;
pub const NET_SERVICE_CONTROL_TCP_BIND: Word = 33;

pub const TCP_RX_META_LEN: Word = 12;
