[package]
name = "nanami-native-performance-tests"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "heap-tests.rs"

[[test]]
name = "hotpaths"
path = "hotpath-tests.rs"

[[test]]
name = "framebuffer"
path = "framebuffer-tests.rs"

[[test]]
name = "honoka-motion"
path = "honoka-motion/main.rs"

[[test]]
name = "graphics-profile"
path = "graphics-profile.rs"

[[test]]
name = "alter-framebuffer"
path = "alter-framebuffer.rs"

[[test]]
name = "alpha-alter"
path = "alpha-alter-tests.rs"

[[test]]
name = "posix-io"
path = "posix-io/main.rs"

[[test]]
name = "core-process"
path = "core-process-tests.rs"

[[test]]
name = "system-version"
path = "system-version.rs"

[[test]]
name = "honoka-info-panel"
path = "honoka-info-panel.rs"

[[test]]
name = "timers"
path = "timer-tests.rs"

[[test]]
name = "hpet"
path = "hpet-tests.rs"

[[test]]
name = "linux-clocks"
path = "linux-clocks.rs"

[[test]]
name = "ipc-notifications"
path = "ipc/main.rs"

[[test]]
name = "storage"
path = "storage/main.rs"

[[test]]
name = "input-distribution"
path = "input-distribution-tests.rs"

[[test]]
name = "network"
path = "network/main.rs"

[[test]]
name = "usb"
path = "usb/main.rs"

[[test]]
name = "usb-pci"
path = "usb/pci.rs"

[[test]]
name = "usb-storage"
path = "usb/storage.rs"

[[test]]
name = "usb-discovery"
path = "usb-discovery/main.rs"

[[test]]
name = "physical-memory"
path = "physical-memory-tests.rs"

[[test]]
name = "acpi"
path = "acpi-tests.rs"

[[test]]
name = "mmio-requests"
path = "mmio-requests.rs"

[dependencies]
nanami-gpt = { path = "../../nanami/servers/libs/gpt" }
a9n-types = "0.3.0"
rlsf = { version = "=0.2.3", default-features = false, features = ["unstable"] }

[dev-dependencies]
fontdue = { version = "=0.9.3", default-features = false, features = ["hashbrown"] }
uefi = { version = "=0.35.0", default-features = false }

[workspace]
