[package]
name = "nanami-native-performance-tests"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "heap-tests.rs"

[[test]]
name = "hotpaths"
path = "hotpath-tests.rs"

[[test]]
name = "alpha-alter"
path = "alpha-alter-tests.rs"

[[test]]
name = "posix-io"
path = "posix-io/main.rs"

[[test]]
name = "core-process"
path = "core-process-tests.rs"

[[test]]
name = "timers"
path = "timer-tests.rs"

[[test]]
name = "storage"
path = "storage/main.rs"

[[test]]
name = "input-distribution"
path = "input-distribution-tests.rs"

[[test]]
name = "network"
path = "network/main.rs"

[dependencies]
rlsf = { version = "=0.2.3", default-features = false, features = ["unstable"] }

[workspace]
