use crate::Word;

pub const BLOCK_DEVICE_REQUEST_CONTROL: Word = 0x9001;
pub const BLOCK_DEVICE_REQUEST_READ: Word = 0x9002;
pub const BLOCK_DEVICE_REQUEST_WRITE: Word = 0x9003;

pub const BLOCK_DEVICE_CONTROL_ATTACH_SHARED_MEMORY: Word = 1;
pub const BLOCK_DEVICE_CONTROL_GET_INFO: Word = 2;

pub const BLOCK_DEVICE_DEFAULT_SHM_BYTES: Word = 0x4000;
pub const BLOCK_DEVICE_BLOCK_SIZE: Word = 1024;
